# Generated by Django 4.2.1 on 2023-06-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orindosh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_soni', models.CharField(max_length=100)),
                ('sana', models.CharField(max_length=100)),
                ('ish_beruvchi', models.CharField(max_length=100)),
                ('xodim', models.CharField(max_length=100)),
                ('korxona', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=100)),
                ('hissa', models.CharField(max_length=100)),
                ('orindoshlik', models.CharField(max_length=100)),
                ('muddatli_mehnat', models.CharField(max_length=100)),
                ('ish_boshlash', models.CharField(max_length=100)),
                ('tomom_bolishi', models.CharField(max_length=100)),
                ('sinov_muddati', models.CharField(max_length=100)),
                ('ish_vaqti', models.CharField(max_length=100)),
                ('kun', models.CharField(max_length=100)),
                ('soat', models.CharField(max_length=100)),
                ('razryad', models.CharField(max_length=100)),
                ('kalemdar', models.CharField(max_length=100)),
                ('kalemdar1', models.CharField(max_length=100)),
                ('kalemdar2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_soni', models.CharField(max_length=100)),
                ('sana', models.CharField(max_length=100)),
                ('ish_beruvchi', models.CharField(max_length=100)),
                ('xodim', models.CharField(max_length=100)),
                ('korxona', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=100)),
                ('asosiy_ish', models.CharField(max_length=100)),
                ('muddatli_mehnat', models.CharField(max_length=100)),
                ('ish_boshlash', models.CharField(max_length=100)),
                ('tomom_bolishi', models.CharField(max_length=100)),
                ('sinov_muddati', models.CharField(max_length=100)),
                ('ish_vaqti', models.CharField(max_length=100)),
                ('kun', models.CharField(max_length=100)),
                ('soat', models.CharField(max_length=100)),
                ('razryad', models.CharField(max_length=100)),
                ('kalemdar1', models.CharField(max_length=100)),
                ('kalemdar2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shartnoma_soni', models.CharField(max_length=100)),
                ('sana', models.CharField(max_length=100)),
                ('ish_beruvchi', models.CharField(max_length=100)),
                ('xodim', models.CharField(max_length=100)),
                ('korxona', models.CharField(max_length=100)),
                ('lavozim', models.CharField(max_length=100)),
                ('asosiy_ish', models.CharField(max_length=100)),
                ('muddatli_mehnat', models.CharField(max_length=100)),
                ('ish_boshlash', models.CharField(max_length=100)),
                ('tomom_bolishi', models.CharField(max_length=100)),
                ('sinov_muddati', models.CharField(max_length=100)),
                ('ish_vaqti', models.CharField(max_length=100)),
                ('kun', models.CharField(max_length=100)),
                ('soat', models.CharField(max_length=100)),
                ('razryad', models.CharField(max_length=100)),
                ('kalemdar1', models.CharField(max_length=100)),
                ('kalemdar2', models.CharField(max_length=100)),
            ],
        ),
    ]
