# Generated by Django 4.2.1 on 2023-06-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orindosh_author_profesir_author_xodimlar_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='hissa',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
