# Generated by Django 4.2.1 on 2023-06-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_xodimlar_hissa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orindosh',
            name='ish_beruvchi',
        ),
        migrations.RemoveField(
            model_name='profesir',
            name='ish_beruvchi',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='ish_beruvchi',
        ),
    ]
