# Generated by Django 4.2.1 on 2023-06-19 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_orindosh_ish_beruvchi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelishuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('joy', models.CharField(max_length=100)),
                ('ish_b', models.CharField(max_length=100)),
                ('fio', models.CharField(max_length=100)),
                ('kelish', models.CharField(max_length=100)),
                ('tuz', models.CharField(max_length=100)),
                ('sabab', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('taraf', models.CharField(max_length=100)),
                ('raqam', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=100)),
                ('aval', models.CharField(max_length=100)),
                ('yangi', models.CharField(max_length=100)),
                ('data1', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
